### ISSUE TITLE
Feature Request: Allow users to provide their own NetworkDispatcher and extract Ktor dependency into a separate artifact

### ISSUE THREAD

**Issue by ankushg** [growthbook/growthbook-kotlin#39]
Ktor can be a pretty heavy dependency in apps that already have networking stacks

We're using [this approach](https://benasher.co/kotlin-multiplatform-networking/) to tie networking within KMP to our existing networking stack

It would be great to be able to provide my own `NetworkDispatcher` implementation and avoid Ktor

**Comment by Bohdan-Kim** [comment]
@way2jatin
What do you think about removing ktor dependency and consuming library users implementions of NetworkDispatcher?

**Comment by Bohdan-Kim** [comment]
So, according to the request, 'ktor-client-core' dependency should be removed. This also leads to removing @DelicateCoroutinesApi annotation, because 'ktor-client-core' transitively depends on 'kotlinx-coroutines-core-jvm'.
![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/08f2548e-94f5-4f8c-a91d-b27a4ba1a75a)

@DelicateCoroutinesApi annotation is used through the entire our codebase.
@ankushg @way2jatin Do you prefer to get rid of this annotation or to leave it and have 'kotlinx-coroutines-core' dependency?

![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/e4efa282-6a6e-475a-a4b7-a65d41d92bda)

![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/98355060-dbd6-4773-b68e-11f275e789ab)

**Comment by AlParhimchik** [comment]
@Bohdan-Kim 
Can you please change `GBSDKBuilderApp`constructor api and pass `networkDispatcher` as a param. And also make `CoreNetworkClient` class public. It will allow us to exclude `ktor` library dependency from our app and also Proguard will remove unused `CoreNetworkClient` class.

**Comment by Bohdan-Kim** [comment]
> 

Sure
Should it look like [this](https://github.com/growthbook/growthbook-kotlin/pull/70)?

**Comment by Bohdan-Kim** [comment]
In [this pull request](https://github.com/growthbook/growthbook-kotlin/pull/70) `networkDispatcher` was moved to `GBSDKBuilder` params.
If app already has networking stack `NetworkDispatcher` implementation can be passed through `GBSDKBuilder` parameters. `ktor` dependency from GrowthBook Kotlin SDK will be optimized and removed in such case.
