### ISSUE TITLE
[Feature] File-based cache (or another persisted strategy)

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook-kotlin#67]
Customers have expressed they would like the same cacheing behaviour on Android as it is on iOS:

- Android appears to cache in-memory
- iOS appears to cache to [disk](https://github.com/growthbook/growthbook-swift/blob/main/Sources/CommonMain/Caching/CachingManager.swift#L17-L19)

This would be great to avoid unnecessary network calls on mobile.

Question/Idea: Would it make sense to expose some kind of cache strategy interface, and allow users to implement their own cache strategy, and if not provided, we can use the existing in-memory one?

**Comment by Bohdan-Kim** [comment]
CachingAndroid class also saves in file:
![image](https://github.com/growthbook/growthbook-kotlin/assets/135710078/78f98a8f-189f-4ff4-a43e-00c5d686d4fc)

**Comment by tinahollygb** [comment]
Thanks for clarifying @Bohdan-Kim – Maybe this is a question of documentation then, because a customer said the following about the Kotlin SDK:

> Features loaded every time we start the application as there is no caching layer unlike in iOS SDK

To them, it doesn't appear to be using a cache. Is it possible it's not implemented in the required way? If so, do we have any documentation that specifically point out how to implement it to get the benefit of the cache?

**Comment by Bohdan-Kim** [comment]
Features are really loaded every time we start the application but before that the library loads features from file. 
I just checked it If there is no Internet features from file only will be present. 
I agree that we need to document how this KMM caching works.

Back to the customer. I suppose the customer wants network calls not on every app start but  once a day for example. Then maybe we need to add new argument "update frequency" which takes an enum for example once a day, once a week and once a month.
Or should we add some interface?

**Comment by tinahollygb** [comment]
Why is the customer experiencing different behaviour of fetching on startup between iOS and Android? Is the native implementation on iOS different than on Android? Or is it possible it's implemented differently?

Documenting how the fetching, cacheing, and refresh behaviour works would be great. We do this in other SDK's (Java is a good example of that) and we also have a generic explanation in the FAQs.

With regards to frequency, I'll ask what they're looking for, though I'm hesitant to change the context API as it will start to deviate from other SDK's.

**Comment by Bohdan-Kim** [comment]
We discussed this with iOS team. The iOS team said that their SDK are making calls on app startup too.
It seems like the Swift code reads data from file and then makes API call:
https://github.com/growthbook/growthbook-swift/blob/main/Sources/CommonMain/Features/FeaturesViewModel.swift#L41C42-L41C48

**Comment by tinahollygb** [comment]
The customer also left this info:

> on android [...] if the feature flag as an example true, and we killed the app and restated it, it comes back to default value which is false.

They had mentioned a 3 second timeout for the first feature response to load. It looks like the cache is not being read when evaluating the feature the very first time, e.g. maybe the cache is being ignored?

Can your team help with an implementation where they can get what they're expecting? An Android implementation example that uses the feature cache before the features are fetched would be great.

**Comment by tinahollygb** [comment]
Is there a way to subscribe to an SDK-ready state? I'm wondering if there's a possible race condition the customer is experiencing, e.g. they are perhaps fetching a feature value before the features have loaded from the cache.

**Comment by Bohdan-Kim** [comment]
In order to fetch a value fetchFeatures() method should be called. To call this method FeaturesViewModel should be created. FeaturesViewModel class is internal for module (it is Kotlin feature), so customer have no ability to instansiate it. 

I see that Java SDK has other structure, in our SDK fetchFeatures() is called from GrowthBookSDK constructor and I see no other way to call it.

So, it should not be a race condition because in our SDK client have no ability to fetch features manually.

**Comment by Bohdan-Kim** [comment]
When cellular network is on the features are loaded from API quite quickly, so an Android implementation example that uses the feature cache before the features are fetched is not clear thing, while we can put an Android implementation example that uses the feature cache when cellular network is off.

An Android implementation example was [uploaded to the repository with examples](https://github.com/growthbook/examples/pull/45).

In order to prove that Kotlin SDK has caching layer it's better to change boolean value from example application to string value. When you turn off Internet like in [this video record](https://drive.google.com/file/d/16DxtDK3tWOgUT2dtqVlaYu0N0-rlO1X6/view?usp=sharing) on thirteenth second and restart the application the value is read from file like in [the video](https://drive.google.com/file/d/16DxtDK3tWOgUT2dtqVlaYu0N0-rlO1X6/view?usp=sharing). When you clear app storage like in the video record on 46 second the value is null because the file with the cache was cleared. When you turn on Internet again like in [the video record](https://drive.google.com/file/d/16DxtDK3tWOgUT2dtqVlaYu0N0-rlO1X6/view?usp=sharing) on 1:11 the value "GrowthBook Kotlin SDK has caching layer" is fetched again.

Availability of the value when Internet is off and value  absence when storage has been cleared proves that value is cached.
